apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-exporter
  labels:
    app.kubernetes.io/name: postgresql-exporter
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql-exporter
        app.kubernetes.io/part-of: opentelemetry-demo
    spec:
      containers:
        - name: exporter
          image: prometheuscommunity/postgres-exporter:v0.20.1
          env:
            - name: DATA_SOURCE_URI
              value: postgresql.demo.svc:5432/otel?sslmode=disable
            - name: DATA_SOURCE_USER
              value: root
            - name: DATA_SOURCE_PASS
              value: otel
          ports:
            - name: metrics
              containerPort: 9187
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-exporter
  labels:
    app.kubernetes.io/name: postgresql-exporter
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  selector:
    app.kubernetes.io/name: postgresql-exporter
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql-exporter
  labels:
    app.kubernetes.io/part-of: opentelemetry-demo
    monitoring: datastore
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
      scrapeTimeout: 8s
