apiVersion: v1
kind: Service
metadata:
  name: hub-tempo
  namespace: observability
spec:
  ports:
    - {name: http, port: 3200, targetPort: 30200}
    - {name: otlp-grpc, port: 4317, targetPort: 30417}
