apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - hub-endpoint/mimir-service.yaml
  - hub-endpoint/loki-service.yaml
  - hub-endpoint/tempo-service.yaml
  - alloy/service-account.yaml
  - alloy/cluster-role.yaml
  - alloy/cluster-role-binding.yaml
  - alloy/deployment.yaml
  - alloy/service.yaml
  - alloy/service-monitor.yaml
configMapGenerator:
  - name: alloy-config
    namespace: observability
    files:
      - config.alloy=alloy/config.alloy
generatorOptions:
  disableNameSuffixHash: true
