apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy
  namespace: observability
  labels:
    app: alloy
spec:
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app: alloy
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 8s
